**1)Write a python program to display all the header tags from wikipedia.org.**

In [1]:
import requests
from bs4 import BeautifulSoup

# scraping a wikipedia article
url_link = 'https://en.wikipedia.org/wiki/Main_Page'
request = requests.get(url_link)

Soup = BeautifulSoup(request.text, 'lxml')

# creating a list of all common heading tags 
heading_tags = ['h1','h2','h3','h4','h5','h6','h7']
for tags in Soup.find_all(heading_tags):
    print(tags.name + '-->'+ tags.text.strip() )

h1-->Main Page
h1-->Welcome to Wikipedia
h2-->From today's featured article
h2-->Did you know ...
h2-->In the news
h2-->On this day
h2-->Today's featured picture
h2-->Other areas of Wikipedia
h2-->Wikipedia's sister projects
h2-->Wikipedia languages

**2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year 
of release) and make data frame.**

In [2]:
# importing the required liabraries 
from bs4 import BeautifulSoup
import requests
import re 
import pandas as pd

#Downloading the imdb top rated 100 movie's data
url_link = 'https://www.imdb.com/list/ls091520106/'
response = requests.get(url_link)
soup = BeautifulSoup(response.text,"html.parser")
soup

# creating empty lists to store the data\
names = []
years = []
ratings = []

#movie items
movie_items = soup.find_all('div',class_='lister-item-content')

# iterating over each movie
for movie in movie_items:
    #name
    name =  movie.find('a').text.strip()
    names.append(name)
    
    #ratings
    rating = movie.find('span', class_='ipl-rating-star__rating').text.strip()
    ratings.append(float(rating))
    
    #year of realease
    year= movie.find('span',class_='lister-item-year').text.strip()
    years.append(year)
    
# creating dataframe 
df = pd.DataFrame({'Names':names, 'Rating': ratings, 'Year of Release':years})

print(df)

                                  Names  Rating Year of Release
0              The Shawshank Redemption     9.3          (1994)
1                         The Godfather     9.2          (1972)
2                 The Godfather Part II     9.0          (1974)
3                       The Dark Knight     9.0          (2008)
4                          12 Angry Men     9.0          (1957)
..                                  ...     ...             ...
95                   North by Northwest     8.3          (1959)
96                   A Clockwork Orange     8.3          (1971)
97                               Snatch     8.2          (2000)
98  Le fabuleux destin d'Amélie Poulain     8.3          (2001)
99                              The Kid     8.2          (1921)

[100 rows x 3 columns]

**3) Write a python program to scrape mentioned details from dineout.co.in : i) Restaurant name 
ii) Cuisine iii) Location iv) Ratings v) Image URL.**

In [3]:
import requests
from bs4 import BeautifulSoup

url_link= 'https://www.dineout.co.in/delhi-restaurants/buffet-special'

page = requests.get(url_link)
page




# In[15]:


soup = BeautifulSoup(page.content)
soup


# In[18]:


first_title = soup.find('div',class_='restnt-info cursor')
first_title.text


# In[20]:


titles = []
for i in soup.find_all('div',class_ ="restnt-info cursor"):
    titles.append(i.text)
location = []
for i in soup.find_all('div',class_="restnt-loc ellipsis"):
    location.append(i.text)
    
location

ratings = []
for i in soup.find_all('div',class_="restnt-rating rating-4"):
    ratings.append(i.text)
    
ratings

detail_info_cuisine_accomodation   = []
for i in soup.find_all('span',class_="double-line-ellipsis"):
    detail_info_cuisine_accomodation .append(i.text)
    
detail_info_cuisine_accomodation 


images = []
for i in soup.find_all('img',class_="no-img"):
    images.append(i['data-src'])
print(len(titles),len(location),len(ratings),len(images))
import pandas as pd
df = pd.DataFrame({'Titles':titles,'Location':location,'Ratings':ratings,'Images':images})
df

7 7 7 7

,Titles,Location,Ratings,Images
0,"Castle's BarbequeConnaught Place, Central Delhi","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
1,"Cafe KnoshThe Leela Ambience Convention Hotel,...","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
2,"India GrillHilton Garden Inn,Saket, South Delhi","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
3,"The Barbeque CompanyGardens Galleria,Sector 38...","Gardens Galleria,Sector 38A, Noida",3.9,https://im1.dineout.co.in/images/uploads/resta...
4,"Delhi BarbequeTaurus Sarovar Portico,Mahipalpu...","Taurus Sarovar Portico,Mahipalpur, South Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
5,The Monarch - Bar Be Que VillageIndirapuram Ha...,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
6,"The Barbeque TimesM2K Corporate Park,Sector 51...","M2K Corporate Park,Sector 51, Gurgaon",4.1,https://im1.dineout.co.in/images/uploads/resta...

**4) Write s python program to display list of respected former finance minister of India(i.e. 
 Name , Term of office) from https://presidentofindia.nic.in/former-presidents and make 
 data frame**

In [4]:
import requests
from bs4 import BeautifulSoup

url_link= 'https://presidentofindia.nic.in/former-presidents'

page = requests.get(url_link)
page

soup = BeautifulSoup(page.content)
soup
#initilazating empty list to store 
names=[]
terms=[]
president_items =soup.find_all('div',class_="president-listing")

#data extracting for each president
for president in president_items:
    
    name = president.find('h3').text.strip()
    names.append(name)

    term_of_office = president.find('h5').text.strip()
    terms.append(term_of_office)

import pandas as pd
df = pd.DataFrame({'Name of the President':names,'Term ':terms})
df

           Name of the President                    Term
0           Shri Ram Nath Kovind  14th President of India
1          Shri Pranab Mukherjee  13th President of India
2   Smt Pratibha Devisingh Patil  12th President of India
3         DR. A.P.J. Abdul Kalam  11th President of India
4           Shri K. R. Narayanan  10th President of India
5        Dr Shankar Dayal Sharma  9th  President of India
6            Shri R Venkataraman   8th President of India
7               Giani Zail Singh   7th President of India
8      Shri Neelam Sanjiva Reddy   6th President of India
9       Dr. Fakhruddin Ali Ahmed   5th President of India
10  Shri Varahagiri Venkata Giri   4th President of India
11              Dr. Zakir Husain   3rd President of India
12  Dr. Sarvepalli Radhakrishnan   2nd President of India
13           Dr. Rajendra Prasad   1st President of India